SET LINESIZE 200
SET PAGESIZE 15
TTITLE CENTER 'Report of Employee' SKIP 1
BTITLE CENTER 'End of Report'
COLUMN EMPLOYEE_ID      HEADING 'EMPLOYEE ID'
COLUMN EMPLOYEE_NAME    HEADING 'EMPLOYEE NAME'
COLUMN JOB_TITLE        HEADING 'JOB TITLE'
COLUMN MANAGER_ID       HEADING 'MANAGER ID'
COLUMN DATE_HIRED       HEADING 'DATE HIRED'
COLUMN DEPARTMENT_ID    HEADING 'DEPARTMENT ID'
COLUMN SALARY FORMAT $999,990
select EMPLOYEE_ID,EMPLOYEE_NAME,JOB_TITLE,MANAGER_ID,TO_CHAR(DATE_HIRED,'DD/MM/YY') DATE_HIRED,DEPARTMENT_ID,SALARY 
from tommy.employees where department_id = &department_id;